org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.code.style=official

android.useAndroidX=true
android.nonTransitiveRClass=true

GROUP=com.migrosone.uilibrary
VERSION_NAME=0.1.4-SNAPSHOT

PUBLISHING_INCEPTION_YEAR=2026
PUBLISHING_URL=https://github.com/migrosone/migrosone-ui-library
PUBLISHING_LICENSE_NAME=The Apache License, Version 2.0
PUBLISHING_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
PUBLISHING_LICENSE_DIST=repo
PUBLISHING_SCM_URL=https://github.com/migrosone/migrosone-ui-library
PUBLISHING_SCM_CONNECTION=scm:git:git://github.com/migrosone/migrosone-ui-library.git
PUBLISHING_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/migrosone/migrosone-ui-library.git
PUBLISHING_DEVELOPER_ID=migrosone
PUBLISHING_DEVELOPER_NAME=Migros One
PUBLISHING_DEVELOPER_URL=https://github.com/migrosone
