name: Publish Maven Central

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to publish
        required: true
        default: 0.1.4-SNAPSHOT

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_VERSION_NAME: ${{ inputs.version }}
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_IN_MEMORY_KEY_ID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Verify
        run: ./gradlew :sample:assembleDebug :ui-theme:testDebugUnitTest :ui-compose:testDebugUnitTest lintDebug

      - name: Compile androidTest sources
        run: ./gradlew :ui-theme:compileDebugAndroidTestKotlin :ui-compose:compileDebugAndroidTestKotlin

      - name: Publish to Maven Central
        run: ./gradlew publishToMavenCentral
